[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor
monitor_speed = 115200
monitor_filters = 
    esp32_exception_decoder
    colorize

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3

; Libraries
lib_deps =
    Wire
    SPI
    WiFi
    PubSubClient@^2.8
    ArduinoJson@^6.21.3
    WiFiManager@^2.0.16-rc.2
    NTPClient@^3.2.1
    arduinoFFT@^1.6.2
    HTTPClient
    Update

; Upload settings
upload_speed = 921600
upload_port = COM7  ; Windows COM port

; Filesystem & Partitions
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv  ; OTA-enabled partition scheme

; Generate merged firmware for web flashers (ESP Web Tools)
extra_scripts = post:merge_bins.py